name: Run

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 14 * *"

jobs:

  check_build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: cowsay does not exist
        run: cowsay hello || true

      - name: fortune does not exist
        run: fortune hello || true

      - name: toilet does not exist
        run: toilet hello || true

      - uses: nf-core/setup-nextflow@v1

      # Need older version, as Nextflow DSL1 is used
      #- uses: nf-core/setup-nextflow@v1
      #  with:
      #    version: 22.10.8 

      - name: Run
        run: ./scripts/run.sh

      - name: Show the results
        run: cat results/result.txt 

